name: API Tests for External Project

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose-plugin
          sudo systemctl start docker
          docker --version
          docker compose version

      - name: Launch the external API service
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git external_api
          cd external_api && docker compose up --build -d
          sleep 20  # Увеличили время ожидания
          curl --retry 5 --retry-delay 5 --retry-all-errors -f http://localhost:8080/actuator/health

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run tests with Allure
        run: |
          mvn clean test
          mkdir -p allure-results
          [ -d target/allure-results ] && cp -r target/allure-results/* allure-results/

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.ref_name }}
          path: allure-results/
          retention-days: 1

      - name: Clean up
        if: always()
        run: |
          cd external_api && docker compose down -v || true